[package]
name = "xdrgen"
version = "0.1.3"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
license = "MIT"
description = "XDR codec generator from specification and runtime library"
repository = "https://github.com/jsgf/rust-xdrgen"
readme = "README.md"
keywords = ["encoding", "protocol", "xdr", "rfc4506", "serialization"]

[[bin]]
name = "xdrgen"
path = "src/xdrgen.rs"
test = false
bench = false
doc = false

[dependencies]
peg = "0.3.3"

[dependencies.xdr-codec]
path = "../xdr-codec"
version = "0.1.1"
